---
version: '2.3'
services:
  base: &base
    volumes:
      - .:/go/src/github.com/realestate-com-au/credulous
    working_dir: /go/src/github.com/realestate-com-au/credulous
    build:
      context: .
      dockerfile: Dockerfile-alt
      target: dep

  go:
    <<: *base
    entrypoint: go

  dep:
    <<: *base
    entrypoint: dep

  console:
    <<: *base
    command: "/bin/sh"

  gometalinter:
    <<: *base
    entrypoint: gometalinter

  gofmt:
    <<: *base
    entrypoint: gofmt

  goimports:
    <<: *base
    entrypoint: goimports
