FROM golang:1.9 as dep
RUN go get -u github.com/golang/dep/cmd/dep
RUN go get -u github.com/alecthomas/gometalinter
RUN gometalinter --install


FROM golang:1.9 as builder
COPY --from=dep /go/bin/dep /go/bin/dep

WORKDIR /go/src/github.com/prateeknayak/credulous
COPY . /go/src/github.com/prateeknayak/credulous

RUN dep ensure -v
RUN go test ./...
ARG VERSION=latest

RUN CGO_ENABLED=0 go build -o /build/credulous -ldflags "-X main.version=$VERSION" -v

FROM scratch
COPY --from=builder /build/credulous /app

ENTRYPOINT [ "/app", "--logtostderr=true"]
