[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.11"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"


[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.1.1"

[prune]
  go-tests = true
  unused-packages = true
