

[[constraint]]
  branch = "master"
  name = "github.com/libgit2/git2go"

[[constraint]]
  branch = "master"
  name = "github.com/realestate-com-au/goamz"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"


[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.11"
